[project]
authors = [{name = "Nils Kristensen", email = ""}]
dependencies = ["anemoi-training>=0.13.0,<0.14", "anemoi-models>=0.19.0,<0.20", "anemoi-graphs>=0.9.7,<0.10", "anemoi-datasets>=0.5.34,<0.6"]
name = "anemoi-stormsurge"
requires-python = ">= 3.11"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge", 
	"fortiers", 
	"file:///fs/site7/eccc/cmd/cmd_shared/slib800/conda-cmc/prod", 
	"https://conda.modular.com/max-nightly"]

platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
anemoi_stormsurge = { path = ".", editable = true }

[tool.pixi.tasks]
interp_ssh_orc12_toera5='''
ord_soumet training-data/scripts/launch_pyscript.sh -cpus 256 -cm 690G \
                                                    -mach moira -t 10800 -jn interpolate-ssh.py \
                                                    -args ${PIXI_PROJECT_ROOT} training-data/scripts/interpolate-ssh.py
'''


[tool.pixi.activation.env]
LD_LIBRARY_PATH = "${PIXI_PROJECT_ROOT}/.pixi/envs/default/lib"

[tool.pixi.dependencies]
aether = ">=2026.9.1,<2027"
ipython = ">=9.17.1,<10"
scipy = ">=1.18.1,<2"
libstdcxx-ng = ">=16.2.0,<17"
trimesh = ">=5.1.0,<6"
fasteners = ">=0.20,<0.21"
